title: Nuno Barreiro 
email: your-email@example.com
description: Portugal based programmer and application architect
baseurl: ""
url: "https://www.nunobarreiro.com"
disqus_shortname: lusocoding
google_analytics: UA-109131329-1

plugins:
  - jekyll-feed